apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
  type: LoadBalancer 